definitions:
  scripts:
    - &generate_root_firebase_json
      name: Generate root Firebase.json file
      working_directory: app
      script: |
        echo $ROOT_FIREBASE_JSON | base64 --decode > firebase.json
workflows:
  android-workflow:
    name: Android Workflow
    working_directory: app
    max_build_duration: 120
    environment:
      android_signing:
        - upload-keystore
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.anjasolutions.cutlink"
        GOOGLE_PLAY_TRACK: internal
      flutter: stable
    scripts:
      - *generate_root_firebase_json
      - name: Generate Google-services.json File
        working_directory: app
        script: |
          echo $ANDROID_APP_GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
      - name: Set up local.properties
        working_directory: app
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/app/android/local.properties"
      - name: Get Flutter packages
        working_directory: app
        script: |
          flutter packages pub get
      - name: Set FlutterFire CLI
        working_directory: app
        script: |
          dart pub global activate flutterfire_cli
      - name: Generate .env file
        working_directory: app
        script: |
          echo $VAR_ENV | base64 --decode > env/.env.prod
      - name: Show Vars
        script: |
          #!/bin/sh
          set -ex
          printenv
      - name: Take a look at Google-services.json File
        script: |
          echo $ANDROID_APP_GOOGLE_SERVICES_JSON | base64 --decode
      - name: Flutter Clean
        working_directory: app
        script: |
          flutter clean
      - name: Flutter Build App Bundle
        working_directory: app
        script: |
          flutter build appbundle --release \
          --dart-define=FIREBASE_OPTIONS_MESSAGING_SENDER_ID=$FIREBASE_OPTIONS_MESSAGING_SENDER_ID \
          --dart-define=FIREBASE_OPTIONS_ANDROID_API_KEY=$FIREBASE_OPTIONS_ANDROID_API_KEY \
          --dart-define=FIREBASE_OPTIONS_WEB_AUTH_DOMAIN=$FIREBASE_OPTIONS_WEB_AUTH_DOMAIN \
          --dart-define=FIREBASE_OPTIONS_PROJECT_ID=cutlink-$FIREBASE_OPTIONS_PROJECT_ID \
          --dart-define=FIREBASE_OPTIONS_ANDROID_APP_ID=$FIREBASE_OPTIONS_ANDROID_APP_ID \
          --dart-define=FIREBASE_OPTIONS_WEB_APP_KEY=$FIREBASE_OPTIONS_WEB_APP_KEY \
          --dart-define=FIREBASE_OPTIONS_WEB_APP_ID=$FIREBASE_OPTIONS_WEB_APP_ID \
          --build-name=1.0.$PROJECT_BUILD_NUMBER \
          --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false
