services:
  app:
    build:
      context: .      
    container_name: cutlink-app
    image: cutlink-app
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
     - cutlink-network    
    restart: always
      
  redis:
    image: redis:alpine
    container_name: cutlink-redis
    ports: 
      - "6379:6379"
    networks:
      - cutlink-network
    restart: always
    volumes:
      - redis-data:/data  # Volume definition to persist Redis data

networks:
  cutlink-network:
    driver: bridge

volumes:
  redis-data:  # This defines a named volume