services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cutlink
    ports:
      - "8080:8080"
    depends_on:
      - redis    
      
  redis:
    image: redis:alpine    