services:
  app:
    build:
      context: .
      dockerfile: Dockerfile      
    container_name: cutlink
    platform: linux/amd64
    ports:
      - "8080:8181"
    depends_on:
      - redis
    networks:
     - cutlink-network
      
  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - "6379:6379"
    networks:
      - cutlink-network
    volumes:
      - redis-data:/data  # Volume definition to persist Redis data

networks:
  cutlink-network:
    driver: bridge

volumes:
  redis-data:  # This defines a named volume