services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cutlink
    ports:
      - "8080:8181"
    depends_on:
      - redis    
      
  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"