services:
  app:
    build:
      context: .      
    container_name: cutlink-api
    image: cutlink-api
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
     - cutlink-network    
    restart: always
    environment:
      - ALLOWED_ORIGINS=https://short.cutli.ink
      - SHORTENED_BASE_URL=https://cutli.ink/
      
  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - "6379:6379"
    networks:
      - cutlink-network
    restart: always
    volumes:
      - redis-data:/data

networks:
  cutlink-network:
    driver: bridge

volumes:
  redis-data: